package com.example.BornToFly;

public enum ObjectType {
    BOOSTER_ARROW,
    SLOWER_T_SHIRTS, SLOWER_SHORTS, SLOWER_BALLOON,
    BARRIER_CENTER_BALCONY, BARRIER_LEFT_BALCONY, BARRIER_RIGHT_BALCONY, BARRIER_HELICOPTER,
    MAN;
}
